<img src="https://numpy.org/images/logos/numpy.svg" max height="15px">

https://numpy.org/

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


#### Numpy Arrays

* Vectors - 2 dim
* Matrices - > 2 dim

#### Creating numpy arrays

In [2]:
my_list = [1,2,3]

my_list

[1, 2, 3]

In [3]:
type(my_list)

list

#### Import numpy

In [4]:
import numpy as np

In [6]:
print(np.__version__)

1.19.5


In [8]:
arr = np.array(my_list)

arr

array([1, 2, 3])

In [9]:
type(arr)

numpy.ndarray

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
type(my_matrix)

list

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Built in methods

*arange*

Returns evenly spaced values in a given interval

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.arange(5,100,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

##### zeros and ones

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

##### linspace

returns evenly spaced numbers over a specified interval

In [20]:
np.linspace(0,11,3)

array([ 0. ,  5.5, 11. ])

In [21]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

##### eye

returns identity matrix

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Generting random numbers

#### rand

Creates an array of given shape and then populates it with random samples of uniform distribution over [0,1]

In [24]:
np.random.rand(3)

array([0.54779651, 0.08524637, 0.65426847])

In [25]:
np.random.rand(3,3)

array([[0.70165898, 0.3822315 , 0.03580299],
       [0.8790435 , 0.45476644, 0.07820949],
       [0.42839415, 0.02481024, 0.8318796 ]])

#### randn

returns a sample with standard normal distribution

In [26]:
np.random.randn(2)

array([-0.86597717,  0.31744808])

In [27]:
np.random.randn(2,2)

array([[-0.08544561, -0.81577774],
       [-0.23965782, -0.69250504]])

#### randint

generate random integers

In [28]:
np.random.randint(7)

2

In [29]:
np.random.randint(1,10,3)

array([8, 2, 1])

#### Array attributes and  methods 

In [30]:
arr1 = np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr2 = np.random.randint(0,50,10)
arr2

array([38, 31, 36, 15, 29,  7, 20, 23, 17, 41])

In [32]:
arr1.shape

(25,)

In [33]:
arr2.shape

(10,)

**max, min, argmax, argmin**

In [34]:
arr1.max()

24

In [35]:
arr2.min()

7

In [36]:
print(arr2)

arr2.argmax()

[38 31 36 15 29  7 20 23 17 41]


9

In [37]:
print(arr2)

arr2.argmin()

[38 31 36 15 29  7 20 23 17 41]


5

**shape, reshape**

In [38]:
arr1.shape

(25,)

# 

In [40]:
arr3 = arr1.reshape(5,5)

arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr3.shape

(5, 5)

#### dtype 

type of variable in an array

In [42]:
arr1.dtype

dtype('int64')

# Great job !