In [1]:
import numpy as np

In [2]:
np.array([1,2,3]).shape

(3,)

In [3]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).shape

(3, 3)

#### Bracket indexing and selection

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

#### broadcasting

In [7]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

#### 2D array indexing

In [8]:
arr2 = np.arange(0,25).reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr2[3:,2:]

array([[17, 18, 19],
       [22, 23, 24]])

In [10]:
# 18

arr2[3][3]

18

In [11]:
arr2[3,3]

18

In [12]:
arr2[2:4,1:3]

array([[11, 12],
       [16, 17]])

In [20]:
arr2[2:4,1:3]

array([[11, 12],
       [16, 17]])

#### Selection

In [21]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [23]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# Great Job !